apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: localhost:5000/main:1.0
        resources:
          limits:
            memory: "256Mi"
        imagePullPolicy: Always
        env:
          - name: CONTAINER_NAME
            value: "main"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: NodePort
  selector:
    app: main
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: localhost:5000/app1:1.0
        resources:
          limits:
            memory: "256Mi"
        imagePullPolicy: Always
        env:
          - name: CONTAINER_NAME
            value: "app1"
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 6000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: localhost:5000/app2:1.0
        resources:
          limits:
            memory: "256Mi"
        imagePullPolicy: Always
        env:
          - name: CONTAINER_NAME
            value: "app2"
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 7000

